name: actualiza-asignaciones

on:
  workflow_dispatch:

jobs:
  actualizarAsignaciones:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del Repositorio
      uses: actions/checkout@v2

    - name: Actualizar Archivo de Asignaciones
      run: echo "Nueva asignación: [AQUI VA TU CONTENIDO]" > asignaciones.txt

    - name: Commit y Push Cambios
      run: |
        git config --local user.email "accion@github.com"
        git config --local user.name "GitHub Action"
        git add asignaciones.txt
        git commit -m "Actualizar asignaciones [skip ci]"
        git push
